### PR TITLE
Allow users to override CodingManager to customize the abstraction

### PR DESCRIPTION
**Pull request by ferpasri**
Move CodingManager building to DefaultProtocol methods

### CODE REVIEW

**Comment by odipar** [comment]
Looks good. Wonder why you changed the CodingManager to inline the call buildIDs?

**Comment by ferpasri** [comment]
I removed the build action method because it is not building the AbstractIDCustom and I wanted to avoid usages.
But if is more readable to have that additional method I can just make it private.

**Review by pekkakaho — DISMISSED** [review]
Code reviewed, please test properly before merging

**Review by pekkakaho — DISMISSED** [review]
Code reviewed, seems ok

**Review by pekkakaho — APPROVED** [review]
code reviewed

**Pull request merged**
