### PR TITLE
Workaround for supporting Qt desktop applications.

### PR DESCRIPTION
**Pull request by TMenting**

### CODE REVIEW

**Comment by ferpasri** [comment]
System Under Test: https://github.com/tonis-lusmagi/QT_Notepad 

1. Master and this Qt solution branch : Seems that both branches are wrongly detecting some menu items widgets
(Maybe this should be a different issue)
master_bad_recognition_2

2. Master branch derives actions in some Qt widgets of the main windows but is not deriving an action in the OK button.
Also master is correctly ignoring the action derivation of blocked widgets from the posterior panel

master_not_qt

3. This Qt branch derives actions in the main window and also in the OK button.
But is also deriving actions in the widgets of the posterior panel

tycho_not_blocked

**Comment by ferpasri** [comment]
@TMenting What Qt SUT did you use?
So we can test multiple Qt SUTs

**Comment by TMenting** [comment]
@ferpasri That's strange.. I've tested it against my own [Qt application](https://github.com/TMenting/testar-vv-reference).
I just checked it in Spy mode, and it looked fine. This PR mainly enables TESTAR to detect actions. without this fix, TESTAR will not identify available actions because everything will me marked as blocked.

**Comment by ferpasri** [comment]
Thanks, with your Qt app the difference of action derivation is clear (left master, right this Qt branch)
master_vs_tycho_qt

Think I need to test deep with more Qt examples

**Comment by TMenting** [comment]
Note: This PR is embedded in [PR 299](https://github.com/TESTARtool/TESTAR_dev/pull/299).

**Comment by ferpasri** [comment]
This feature is already included in the #299
We will work on integrating the complete visual validation feature, and we close this PR.

**Pull request closed without merging**
