### PR TITLE
Webdriver remote element

### PR DESCRIPTION
**Pull request by odipar**
Added 2 new Actions (WdRemoteClickAction and WdRemoteTypeAction) that use the selenium API.

One can use these Actions if you don't want TEST* to capture the platform's Mouse or Keyboard during GENERATE mode.
Also, HTML options can be interacted with via WdRemoteClickAction, fixing issue #237.

Both Actions need a RemoteWebElement, so a property (remoteWebElement) is added to WdElement, which is populated by testar.state.js.
Next to that, additional properties (selected, checked) have been added to both WdElement and testar.state.js and the value property has been fixed to capture the correct state.

### CODE REVIEW

**Comment by ferpasri** [comment]
It seems that if TESTAR executes a RemoteAction that needs scroll:
1 - scrolling (d.executeScript("arguments[0].scrollIntoView(true)", remoteElement))
2 - clicking (remoteElement.click())

Webdriver throws an exception in the cmd:
- WebDriverException: Element is not clickable at point (x, y). Other element would receive the click

**Comment by odipar** [comment]
Nice find on the carousel elements: I wonder how you found the issue? We could remove the scrolling step, because scrolling is not required for a click to succeed (it does not have to be visible).

**Comment by ferpasri** [comment]
**Issue StaleElementReferenceException**
org.openqa.selenium.StaleElementReferenceException: stale element reference: element is not attached to the page document
https://www.selenium.dev/exceptions/#stale_element_reference

``at org.fruit.alayer.actions.WdRemoteClickAction.<init>(WdRemoteClickAction.java:81)``
``this.set(Tags.Desc, "Remote click " + widget.element.remoteWebElement.getText());``

My idea was to use ``remoteWebElement.getText()`` to prepare the description of the action.
But running TESTAR It seems that if the web elements are not static (example: carousel) from when we infer the State until we derive the actions (using the remoteWebElement), this Text no longer exists in the DOM? and TESTAR fails.

**How to reproduce**
- Run webdriver_remote_webcomponent protocol (www.ou.nl)
- Accept cookies
- Let TESTAR run with spy mode over the carousel of images (www.ou.nl)

**Possible solutions ?**
- Dont use ``remoteWebElement.getText()``, Will other descriptive properties work correctly?
- Catch the exception and customize some text

**Comment by odipar** [comment]
Indeed, RemoteWebElements (ids) are not stable, especially when dealing with dynamic content.
Because `widget.element.remoteWebElement.getText()` actually *resolves* the remote element, it *may* throw an error if the element has become stale.
An easy solution would be to store/get the text of the widget. ie `widget.element.getElementDescription()'.

But I believe that TESTAR has a more generic problem with (very) dynamic. Consider this (very realistic) scenario:

* capture the state of SUT
* identify actionable elements
.... state of SUT changes (i.e. the image carousel)
* click actionable element -> error

Even if we don't use RemoteWebElements, this scenario would be problematic. However, it's aggravated in the case of RemoteWebElements.
To be more robust (across different TEST* sessions) I think we need to introduce 'stable' identifiers. My suggestion would be to use xpaths (with support for shadow DOMs) as stable identifiers. This as opposed to the currently the build-in id scheme with concrete/abstract ids thatare problematic (because they are too precise or too abstract).

With stable ids we can execute a (remote) action by looking up the RemoteWebElement via uts xpath, and then perform the click/key actions. 
Of course, that wouldn't solve the issue for dynamic content, but at least we don't have to consume Webdriver exceptions.

I will propose stable ids in another PR.

**Comment by odipar** [comment]
I don't understand why the CI/CD pipeline is failing: followLinks is a protected member of WebdriverProtocol.
Also everything compiles with gradlew installDist and also after starting TESTAR with sse=webdriver_remove_webelement

**Comment by ferpasri** [comment]
Hi,
We did some updates in the master branch that allow users to use the test.settings in the WebdriverProtocol to configure the web behaviour (css classes, followLinks, etc...). 
The `webdriver_remote_webcomponent` protocol is now updated.

**Comment by odipar** [comment]
ah, of course, i didn't merge with master first. thanks

**Review by oliviarves — APPROVED** [review]

**Pull request merged**
