### PR TITLE
Webdriver CI  java protocol + gradle task

### PR DESCRIPTION
**Pull request by ferpasri**
- TESTAR automatically check and download last chromedriver version using "downloadChromedriver" gradle task
- Added Protocol_test_gradle_workflow_webdriver_generic to check that webdriver:
1. Doesnt contain ou.nl by default
2. WebdriverProtocol.ensuredomain feature adds correctly default ou.nl to domainAllowed
3. ou.nl launchs and TESTAR is able to detect the SuspiciousTitle ".*[oO]nderwijs.*"
- Move workflow protocols to "resources/workflow/settings". Then build and distribution tasks will not copy these protocols ("hidden" for default TESTAR users)
- AlwaysCompile feature also tested at CI level

### CODE REVIEW

**Comment by pekkakaho** [comment]
Tried to run gradlew runTestWebdriverSuspiciousTitle on command line:
- I had a clean build, so there was no SSE file -> opens the protocol selection and waits for the user to react

Build fails:

D:\TESTAR\TESTAR_dev>gradlew runTestWebdriverSuspiciousTitle
Download https://chromedriver.storage.googleapis.com/88.0.4324.96/chromedriver_win32.zip
> Task :testar:runTestWebdriverSuspiciousTitle FAILED

FAILURE: Build failed with an exception.

* Where:
Build file 'D:\TESTAR\TESTAR_dev\testar\build.gradle' line: 345

* What went wrong:
Execution failed for task ':testar:runTestWebdriverSuspiciousTitle'.
>
  Listening for transport dt_socket at address: 5005
  Protocol: test_gradle_workflow_webdriver_generic doesn't exist
  Test settings is <.\settings\desktop_generic\test.settings>
  AlwaysCompile=true
  ApplicationName=webdriver_and_suspicious
  SuspiciousTitles=.*[oO]nderwijs.*
  ShowVisualSettingsDialogOnStartup=false
  Mode=Generate
  Sequences=1
  SequenceLength=2
  Loading external lib ... windows.dll
  [START] Running processes (106):
  SUT is running after <2040> ms ... waiting UI to be accessible
  SUT accessible after <2215> ms
  [END] Running processes (107):
  Will kill process: PID <14028> HANDLE <4084> DESC <notepad.exe>
  2021-02-15-09:48:47.818 webdriver_and_suspicious Generate D:\TESTAR\TESTAR_dev\testar\target\install\testar\bin\output\2021-02-15_09h48m42s_webdriver_and_suspicious\sequences\2021-02-15_09h48m42s_webdriver_and_suspicious_sequence_1.testar OK "No problem detected."

  ERROR: TESTAR didnt connect with WEB_DRIVER

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 38s
28 actionable tasks: 3 executed, 25 up-to-date

**Comment by ferpasri** [comment]
> Tried to run gradlew runTestWebdriverSuspiciousTitle on command line:

I moved the test protocols to "testar/resources/workflow/settings/test_gradle_workflow_webdriver_generic". So the default build task will not copy all the test protocols inside the distribution by default.
To prepare these test workflow protocols we need to run first "init_workflow_test" task.
Try to:

1. Run init_workflow_test
2. Then runTestWebdriverSuspiciousTitle

**Comment by pekkakaho** [comment]
Ok, running on command line:
- gradlew init_workflow_test
- gradlew runTestWebdriverSuspiciousTitle

Opens ou.nl and check suspicious title.

**Review by pekkakaho — APPROVED** [review]
Seems to work as expected.

**Pull request merged**
