### PR TITLE
Extended setting framework

### PR DESCRIPTION
**Pull request by TMenting**
Added a new settings framework to prevent the old `test.settings` from becoming a big monolith.
The extended settings framework is based upon XML files, and with the use of JAXB it should require minimal effort to create new settings.

NOTE: This framework doesn't support duplicate XML tags, when this is required it might be possible to use a List as member of the parent tag. When duplicate tags are used the first element is being used.

This PR might be a first step to solve #100

### CODE REVIEW

**Comment by ferpasri** [comment]
@TMenting Hi Tycho,

- "org.fruit.monkey.SettingsDialog" is using external JavaFx library "javafx.util.Pair"
Seems that is ok for Java Oracle, but OpenJDK has not this Fx library by default

Is it okay to use ? :
- "core -> org.fruit.Pair class" with left() and right() ?
- instead of "javafx.util.Pair" getKey(), getValue() ?

**Comment by TMenting** [comment]
@ferpasri Hi Fernado,
Yes sure you can change it :+1:

**Comment by ferpasri** [comment]
Before merging will be good to integrate the use of command line arguments with these XML ExtendedSettings:
- ExtendedSettingFactory is being initialized inside "SettingsDialog", we need to move this initialization to non-GUI internal method (probably Main.loadSettings).
- Then we need to read cmd arguments and Overwrite XML ExtendedSettings file values.

**Comment by TMenting** [comment]
> * ExtendedSettingFactory is being initialized inside "SettingsDialog", we need to move this initialization to non-GUI internal method (probably Main.loadSettings).

Yes, good idea.

> * Then we need to read cmd arguments and Overwrite XML ExtendedSettings values.

With overwrite, do you mean only the location of the extended settings file or also its content?

**Comment by ferpasri** [comment]
For CI, I think the best is also the content

If default value or XML value is "visualValidationSettings.enabled"=false, 
but users type in the command line something like "visualValidationSettings.enabled"=true, 
we will need to prioritize this cmd argument.

**Comment by TMenting** [comment]
Hi @ferpasri,
I support the idea of overriding these values, but realizing this doesn't fit within my project scope for now.
But feel free to implement this yourself, I'll try to find some time to move the initialization and support the extended settings path override. This should enable override values as well by just generating a different XML file.

**Comment by TMenting** [comment]
@ferpasri I've updated the PR and verified that overriding the path for extended settings is working when running TESTAR from command line. `testar sse=desktop_generic ExtendedSettingsFile="".\\settings\\desktop_generic\\test.xml"" ShowVisualSettingsDialogOnStartup=true Sequences=1 SequenceLength=1 Mode=Generate SUTConnectorValue=" ""C:\\Windows\\notepad.exe"" " SuspiciousTitles=".[eE]rror.|.[eE]xcep[ct]ion."`  I noticed that there is a wiki dedicated to settings for this project. It looks good and was very helpful for me. I noticed on my machine that I needed to double slash the path for SUTConnectorValue, with the example I faced an exception. Perhaps an idea to use a pre-installed app like notepad as example app. Final suggestion for now @pekkakaho , can we enable comments on the wiki?

**Review by ferpasri — APPROVED** [review]
XML with CI feature has been used and tested last months with the RL experiments.
https://github.com/TESTARtool/TESTAR_dev/tree/master_experiments

Example of XML RL settings protocol:
https://github.com/TESTARtool/TESTAR_dev/blob/master_experiments/testar/resources/settings/spaghetti_reinforcement_learning

**Pull request merged**
