### PR TITLE
fix for inputting empty string

### PR DESCRIPTION
**Pull request by pekkakaho**
fix for inputting empty string (bug report by Conny)

### CODE REVIEW

**Comment by pekkakaho** [comment]
Please test if it works correctly before merging

**Comment by CHageluken** [comment]
This is the version I’m currently running

What should be changed?

 

public Action clickAndReplaceText(final Position position, final String text) {

    Assert.notNull(position, text);

    // clicking the widget to select it:

    Builder builder = new CompoundAction.Builder().add(leftClickAt(position), 1);

    // pressing Cntr + A keys to select all text:

    builder.add(new KeyDown(KBKeys.VK_CONTROL), 0.1).add(new KeyDown(KBKeys.VK_A), 0.1).add(new KeyUp(KBKeys.VK_A), 0.1).add(new KeyUp(KBKeys.VK_CONTROL), 0.1);

    // Typing the new text:

    builder.add(new Type(text), 1);

    return builder.build();

  }

 

 

Van: Pekka Aho [mailto:notifications@github.com] 
Verzonden: donderdag 28 februari 2019 08:56
Aan: TESTARtool/TESTAR_dev
CC: CHageluken; Review requested
Onderwerp: Re: [TESTARtool/TESTAR_dev] fix for inputting empty string (#156)

 

Please test if it works correctly before merging

**Comment by pekkakaho** [comment]
You can see the change from "Files changed" - https://github.com/TESTARtool/TESTAR_dev/pull/156/files

The red line has been deleted and the blue lines added.

**Comment by ferpasri** [comment]
Should this be a new clickAndRemoveText Action instead of use this condition in clickAndReplaceText for empty strings?

**Comment by pekkakaho** [comment]
If you append text instead of replacing, there is no problem with inserting empty string. But in replace text, selecting all text with Control+A, and then not typing any text, the previous text is not deleted. This is the fix.

**Comment by ferpasri** [comment]
"If you append text instead of replacing, there is no problem with inserting empty string"
But TESTAR has a specific Assert to prevent this, empty strings are not allowed.

If we want to "replace" existing text for a new empty String, we are deleting the existing text not replacing it.

**Comment by CHageluken** [comment]
Due to the fact that in the Tgherkin method TypeGesture an empty string is replaced with  “’’” an extra condition is needed.

 

   if (text.length() == 0 || "''".equals(text)){ 

     

      System.out.println("wordt deze route gevolgd?");

      //empty string, pressing DEL

      builder.add(new KeyDown(KBKeys.VK_DELETE),0.1);

    } else {

     System.out.println("wordt deze route gevolgd?");

      //empty string, pressing DEL

      builder.add(new Type(text), 1);

    

    }    

 

 

Van: Pekka Aho [mailto:notifications@github.com] 
Verzonden: donderdag 28 februari 2019 14:51
Aan: TESTARtool/TESTAR_dev
CC: CHageluken; Review requested
Onderwerp: Re: [TESTARtool/TESTAR_dev] fix for inputting empty string (#156)

 

If you append text instead of replacing, there is no problem with inserting empty string. But in replace text, selecting all text with Control+A, and then not typing any text, the previous text is not deleted. This is the fix.

**Pull request closed without merging**
