### PR TITLE
Feature: add utf 32 support

### PR DESCRIPTION
**Pull request by GuyT07**
Please review carefully. A lot of changes are involved. First merge https://github.com/TESTARtool/TESTAR_dev/pull/192 (or merge this one only, close 192). This is build on top of that branch. I tested that TESTAR starts and is able to insert 'crazy' characters ;)

### CODE REVIEW

**Comment by ferpasri** [comment]
1. I can't use the manual filter (Caps_lock + mouse over widget + Control) to filter the widgets.
Other keyboard combinations like Shift + down seems to work

**Comment by ferpasri** [comment]
Usability issues.

1. Value "InputFileText" of desktop_xxxxx test.settings files, should be "./settings/desktop_xxxxx/blns.txt" ?

2. The message "Error while reading text input file!" is not friendly to end users. They will see this message all time and they have no information about the error and how to solve it.

**Comment by ferpasri** [comment]
Now that Filter and input works:

1. When TESTAR is doing an input into a text filed (Ex. Notepad), not all the sentence is properly inputed into the SUT, but is properly readed and saved into logs:
(OK) Example from file: "><script>alert(123)</script>
(OK) Readed and saved into logs: "><script>alert(123)</script>
(missing "(" before alert) Inputed: "><script>alert123);</script x="

2. These inputs are saved into the HTML reports and the alerts work well so if someone opens the HTML report to saw it, probably will need to close some windows alerts

**Comment by GuyT07** [comment]
> Now that Filter and input works:
> 
> ISSUES
> 
> 1. When TESTAR is doing an input into a text filed (Ex. Notepad), not all the sentence is properly inputed into the SUT, but is properly readed and saved into logs:
>    (OK) Example from file: "><script>alert(123)</script>
>    (OK) Readed and saved into logs: "><script>alert(123)</script>
>    (missing "(" before alert) Inputed: "><script>alert123);</script x="
> 2. These inputs are saved into the HTML reports and the alerts work well so if someone opens the HTML report to saw it, probably will need to close some windows alerts
> 3. (Master version issue -> #195 )
> 4. With webdriver the special character of the input are not working, maybe some encoder to change into govert_dev and webdriver_dev branch
> 
> ENHANCEMENT:
> 
> 1. Change the alert message from "123" to something like "Error, SUT vulnerable to Cross Site Scripting", then TESTAR will autodetect that like suspicious title.

Issue 1 and 2 are due to characters that are not properly escaped for printing. This results in XSS vulnerabilities you found in the HTML report. I think if we escape those characters properly, 4 is solved as well. For issue 3, I do not have enough context although I think an additional filter may have to be added to filter out the keyboard combinations (maybe only in generation mode?).

**Comment by ferpasri** [comment]
1. 
Filtering all Notepad buttons except text input widget, and using only "<script\x20type="text/javascript">javascript:alert(1);</script>" has text into blns.txt

Debugging:
"core\src\org\fruit\alayer\actions\Type.java" -> method "run" -> to chech the inputted text and characters.
"core\src\org\fruit\alayer\devices\AWTKeyboard.java" -> method -> "press" -> to check robot key values.

This was the result:
[debug_keyCodes.txt](https://github.com/TESTARtool/TESTAR_dev/files/3391190/debug_keyCodes.txt)

Has an example:

Right parenthesis is executed with 4 sub key codes

DEBUG: Type characters : ) equals 41
DEBUG: AWTKeyboard Robot : code : 41
DEBUG: AWTKeyboard Robot : code : 18
DEBUG: AWTKeyboard Robot : code : 100
DEBUG: AWTKeyboard Robot : code : 97

but left parenthesis  is executed only with 1 sub key code

DEBUG: Type characters : ( equals 40
DEBUG: AWTKeyboard Robot : code : 40



3.
a) We want to create a headless setting into TESTAR to enable/disable Keyboard input events, this will solve this problem into CI/CD execution environments.

b) Into other contexts, where a user is learning or executing manually TESTAR, this problem could be worst if a complex String appears.
I was trying to save into a HashSet the KeyEvents executed by the java.awt.Robot, and use this HashSet like a queue to input/remove Events, and try to know if the event is from user or Robot.

https://github.com/TESTARtool/TESTAR_dev/commit/3ce8e3da32e4097fa418be557f081bda89343c73

it seems that this solves the problem of autoexecuted events, but the execution of user commands is not detected as cleanly as before

**Comment by ferpasri** [comment]
Closing this PR because the main ideas were already implemented in the TESTAR master branch:
- Contains a PasteText action that allows inserting special characters
- Contains an InputDataManager class and a custom_input_data.txt file that allows users to custom naughty string values
- Special characters are escaped in the HtmlSequenceReport class

**Pull request closed without merging**
