### PR TITLE
Fixed mouse interaction for webdriver protocol.

### PR DESCRIPTION
**Pull request by TMenting**
I noticed that with the latest merge the mousce actions are not executed correctly when using the webdriver protocol.
Reverted the change that applied the displayscale to the mouse coordinate while using the webdriver protocol. Tested on macbook with different display scales and blurry on/off functions. Needs te be tested on multiple systems including a setup with an additional monitor.

### CODE REVIEW

**Comment by ferpasri** [comment]
It works correctly in my Windows 10 environment with different scale and display options if the blurry option is enabled (it comes enabled by default on Windows 10, version 1903).

We can also overwrite the default value in the settings protocol:
mouse.setCursorDisplayScale(displayScale);

I think the issue here should be to document this and take a decission about:
- Disable it by default (1.0)? and overwrite it in the protocol with displayScale if necessary?
- Enable it by default (displayScale)? and overwrite it to 1.0 if necessary?

**Comment by pekkakaho** [comment]
For my Win10, it works correctly with blurry + 100% but not with blurry + 150%. With 150% the mouse moves in a strange way, not clicking on the selected actions.

**Comment by TMenting** [comment]
@pekkakaho @ferpasri Does this also mean that if you run this branch the mouse actions are not working correctly anymore?

**Comment by TMenting** [comment]
This is what I'm experiencing when running Testar with 150% scaling and fix blurry enabled on commit cd37b4bf4e79d1ae8cb488ade758663ab830b3cc
Homepage-Open-Universiteit-Open-Universiteit-Google-Chrome-2020-02-25-21-14-21

**Comment by ferpasri** [comment]
> @pekkakaho @ferpasri Does this also mean that if you run this branch the mouse actions are not working correctly anymore?

- Webdriver
Master branch:
100% + blurry option enabled = works
100% + blurry option disabled = works

150% + blurry option enabled = works
150% + blurry option disabled = fails, click deviates down-right (is adding display scale by default)
(If I Override with mouse.setCursorDisplayScale(1.0) it works)

This pull request:
100% + blurry option enabled = works
100% + blurry option disabled = works

150% + blurry option enabled = fails, click deviates upper-left (is not adding the display scale and needs it)
(Cannot Override with mouse.setCursorDisplayScale(displayScale), because removed)
150% + blurry option disabled =

**Comment by pekkakaho** [comment]
For me (my recommended is 100%), while testing this pull request with web driver generic protocol on OU web site: 
- blurry + 150% with generate mode, results TESTAR clicking on wrong locations as mouse moves in a funny way (different than not having enough time, that has been another issue, solved by TESTAR settings)

**Comment by TMenting** [comment]
As discussed added the possibility to override the display scale from the settings dialog. The option is only visible when the user selects a protocol that contains the name webdriver. The option is located at the General panel and does only apply on the webdriver protocol.

**Pull request merged**
